import { Inter} from "next/font/google";
import "./globals.css";
// import { ThemeProvider } from "@/components/theme-provider"
import Header from "../components/header";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import { Toaster } from "sonner";
import { ThemeProvider } from "../components/theme-provider";


const inter = Inter({subset: ["latin"]});
export const metadata = {
  title: "Coach Ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
      <ClerkProvider
       appearance={{
        baseTheme: dark,
      }}
      >
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* header  */}
            <Header/>
            <main className="min-h-screen">{children}</main>
                 <Toaster richColors/>
            {/* footer  */}
            <footer className="bg-muted/50 py-12">
              {/* <div className="container mx-auto px-4 text-center text-gray-200">
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis, praesentium.</p>
              </div> */}
            </footer>
          </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
